language: ruby

rvm:
  - 1.9.3
  - 2.0
  - jruby-19mode
env: JRUBY_OPTS="-Xcompile.invokedynamic=false"

before_install: gem install --pre bundler
bundler_args: --without production development

before_script: cp config/database.yml.travis config/database.yml
script: bundle exec rspec

after_success: rake coveralls:push
